server:
  port: 8001

spring:
  application:
    name: modulo-6
  profiles:
    active: dev
  jpa:
    open-in-view: true

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html